apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork-pod
  labels:
    app: hostnetwork-test
spec:
  hostNetwork: true
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.1"
          memory: "64Mi"